In [1]:
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

In [4]:
final=pd.read_csv('C:/Users/user/Documents/chromedownload/데이터셋.csv',encoding='utf-8')

In [5]:
final1=final.replace({'자치구':'강남구'},{'자치구':1})
final2=final1.replace({'자치구':'강동구'},{'자치구':2})
final3=final2.replace({'자치구':'강북구'},{'자치구':3})
final4=final3.replace({'자치구':'강서구'},{'자치구':4})
final5=final4.replace({'자치구':'관악구'},{'자치구':5})
final6=final5.replace({'자치구':'광진구'},{'자치구':6})
final7=final6.replace({'자치구':'구로구'},{'자치구':7})
final8=final7.replace({'자치구':'금천구'},{'자치구':8})
final9=final8.replace({'자치구':'노원구'},{'자치구':9})
final10=final9.replace({'자치구':'도봉구'},{'자치구':10})
final11=final10.replace({'자치구':'동대문구'},{'자치구':11})
final12=final11.replace({'자치구':'동작구'},{'자치구':12})
final13=final12.replace({'자치구':'마포구'},{'자치구':13})
final14=final13.replace({'자치구':'서대문구'},{'자치구':14})
final15=final14.replace({'자치구':'서초구'},{'자치구':15})
final16=final15.replace({'자치구':'성동구'},{'자치구':16})
final17=final16.replace({'자치구':'성북구'},{'자치구':17})
final18=final17.replace({'자치구':'송파구'},{'자치구':18})
final19=final18.replace({'자치구':'양천구'},{'자치구':19})
final20=final19.replace({'자치구':'영등포구'},{'자치구':20})
final21=final20.replace({'자치구':'용산구'},{'자치구':21})
final22=final21.replace({'자치구':'은평구'},{'자치구':22})
final23=final22.replace({'자치구':'종로구'},{'자치구':23})
final24=final23.replace({'자치구':'중구'},{'자치구':24})
final=final24.replace({'자치구':'중랑구'},{'자치구':25})

In [6]:
final.head(26)

자치구  화재건수  인명피해    재산피해        날짜  화재발생      인구    면적  인구밀도(명/㎢)     가정용  \
0     1     3     0    1905  20150102     1  581760  39.5      14728  867871   
1     1     1     0    3910  20150103     1  581760  39.5      14728  867871   
2     1     2     0    1564  20150104     1  581760  39.5      14728  867871   
3     1     0     0       0  20150105     0  581760  39.5      14728  867871   
4     1     1     0      11  20150106     1  581760  39.5      14728  867871   
5     1     3     1   57283  20150107     1  581760  39.5      14728  867871   
6     1     1     0     181  20150108     1  581760  39.5      14728  867871   
7     1     3     0    3251  20150109     1  581760  39.5      14728  867871   
8     1     0     0       0  20150110     0  581760  39.5      14728  867871   
9     1     1     0      80  20150111     1  581760  39.5      14728  867871   
10    1     2     0      89  20150112     1  581760  39.5      14728  867871   
11    1     0     0       0  20150113     0  581760  39.5      14728  867871   
12    1     3     0    4673  20150114     1  581760  39.5      14728  867871   
13    1     3     0    4673  20150115     1  581760  39.5      14728  867871   
14    1     1     0  282278  20150116     1  581760  39.5      14728  867871   
15    1     1     0    1584  20150117     1  581760  39.5      14728  867871   
16    1     2     0     172  20150118     1  581760  39.5      14728  867871   
17    1     1     0    6345  20150119     1  581760  39.5      14728  867871   
18    1     1     0      23  20150120     1  581760  39.5      14728  867871   
19    1     2     0    5404  20150121     1  581760  39.5      14728  867871   
20    1     0     0       0  20150122     0  581760  39.5      14728  867871   
21    1     1     0      82  20150123     1  581760  39.5      14728  867871   
22    1     2     0     100  20150124     1  581760  39.5      14728  867871   
23    1     3     0     607  20150125     1  581760  39.5      14728  867871   
24    1     1     0     239  20150126     1  581760  39.5      14728  867871   
25    1     1     0     488  20150127     1  581760  39.5      14728  867871   

      공공용     서비스업    산업용       노후도         습도        기온        풍속        강수  
0   99263  3644486  17713  0.590889  43.041667 -4.679167  1.970833  0.000000  
1   99263  3644486  17713  0.590889  57.000000  0.166667  1.216667  0.000000  
2   99263  3644486  17713  0.590889  73.208333  2.504167  1.100000  0.000000  
3   99263  3644486  17713  0.590889  69.541667  4.304167  1.600000  0.166667  
4   99263  3644486  17713  0.590889  35.583333 -4.058333  2.400000  0.000000  
5   99263  3644486  17713  0.590889  33.625000 -4.054167  1.550000  0.000000  
6   99263  3644486  17713  0.590889  46.500000 -2.858333  1.550000  0.000000  
7   99263  3644486  17713  0.590889  52.125000 -0.470833  1.600000  0.000000  
8   99263  3644486  17713  0.590889  61.458333  2.166667  1.762500  0.000000  
9   99263  3644486  17713  0.590889  43.500000 -1.095833  2.225000  0.000000  
10  99263  3644486  17713  0.590889  40.958333 -1.225000  1.333333  0.000000  
11  99263  3644486  17713  0.590889  39.291667  1.991667  1.183333  0.000000  
12  99263  3644486  17713  0.590889  38.541667  3.929167  0.937500  0.000000  
13  99263  3644486  17713  0.590889  59.625000  4.133333  1.470833  0.000000  
14  99263  3644486  17713  0.590889  63.000000 -0.387500  2.916667  0.000000  
15  99263  3644486  17713  0.590889  45.166667 -2.491667  1.966667  0.000000  
16  99263  3644486  17713  0.590889  73.291667  1.079167  1.854167  0.416667  
17  99263  3644486  17713  0.590889  59.416667 -0.545833  1.825000  0.000000  
18  99263  3644486  17713  0.590889  51.916667  1.050000  1.287500  0.000000  
19  99263  3644486  17713  0.590889  55.416667  3.904167  0.979167  0.000000  
20  99263  3644486  17713  0.590889  58.291667  3.683333  1.204167  0.000000  
21  99263  3644486  17713  0.590889  62.000000  2.733333  1.579167  0.000000  
22  99263  3644486  17713 

In [7]:
final1=final.drop(['날짜','인명피해','화재건수','재산피해'],axis=1)

In [8]:
final2=final1.drop(['화재발생'],axis=1)

In [9]:
final2.head()

자치구      인구    면적  인구밀도(명/㎢)     가정용    공공용     서비스업    산업용       노후도  \
0    1  581760  39.5      14728  867871  99263  3644486  17713  0.590889   
1    1  581760  39.5      14728  867871  99263  3644486  17713  0.590889   
2    1  581760  39.5      14728  867871  99263  3644486  17713  0.590889   
3    1  581760  39.5      14728  867871  99263  3644486  17713  0.590889   
4    1  581760  39.5      14728  867871  99263  3644486  17713  0.590889   

          습도        기온        풍속        강수  
0  43.041667 -4.679167  1.970833  0.000000  
1  57.000000  0.166667  1.216667  0.000000  
2  73.208333  2.504167  1.100000  0.000000  
3  69.541667  4.304167  1.600000  0.166667  
4  35.583333 -4.058333  2.400000  0.000000

In [10]:
final1.head()

자치구  화재발생      인구    면적  인구밀도(명/㎢)     가정용    공공용     서비스업    산업용  \
0    1     1  581760  39.5      14728  867871  99263  3644486  17713   
1    1     1  581760  39.5      14728  867871  99263  3644486  17713   
2    1     1  581760  39.5      14728  867871  99263  3644486  17713   
3    1     0  581760  39.5      14728  867871  99263  3644486  17713   
4    1     1  581760  39.5      14728  867871  99263  3644486  17713   

        노후도         습도        기온        풍속        강수  
0  0.590889  43.041667 -4.679167  1.970833  0.000000  
1  0.590889  57.000000  0.166667  1.216667  0.000000  
2  0.590889  73.208333  2.504167  1.100000  0.000000  
3  0.590889  69.541667  4.304167  1.600000  0.166667  
4  0.590889  35.583333 -4.058333  2.400000  0.000000

In [11]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(final2, final1['화재발생'], test_size=0.2, random_state=42)

In [12]:
train_x.head()

자치구      인구     면적  인구밀도(명/㎢)     가정용     공공용     서비스업    산업용  \
1715     5  529031  29.57      17891  625389  229112   759011  32377   
26508   23  164257  23.91       6869  250888  195454  1234839  72395   
15967   19  481845  17.41      27681  630303   61393   862823  23623   
17306   23  161922  23.91       6771  251046  247069  1202342  71543   
1741     5  529031  29.57      17891  625389  229112   759011  32377   

            노후도         습도         기온        풍속   강수  
1715   0.700117  58.875000  21.966667  0.733333  0.0  
26508  0.526737  70.875000  23.508333  1.458333  0.0  
15967  0.724200  61.458333  18.675000  1.266667  0.0  
17306  0.516613  45.583333  22.620833  1.633333  0.0  
1741   0.700117  63.958333  17.329167  0.512500  0.0

In [45]:
test_y.head()

33513    1
18670    0
18049    0
31662    1
15573    0
Name: 화재발생, dtype: int64

In [46]:
test_x.shape

(7295, 5)

In [47]:
final2.sample(3)

자치구         습도         기온        풍속   강수
23549   25  75.958333  28.308333  0.770833  0.0
7269    20  61.875000  13.533333  2.162500  0.0
33922   23  69.250000  21.683333  1.383333  0.0

In [48]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=13)
model.fit(train_x, train_y)

C:\Users\user\conda1\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=13, verbose=0,
                       warm_start=False)

In [49]:




predicted = model.predict(test_x)
model.score(test_x, test_y)

0.530637422892392

In [50]:
from sklearn.metrics import roc_auc_score
probabilities = model.predict_proba(test_x)

In [51]:
roc_auc_score(test_y, probabilities[:, 1])

0.535639785239966

In [52]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_y, predicted)

array([[2428, 1345],
       [2079, 1443]], dtype=int64)

In [53]:
#정밀도
from sklearn.metrics import precision_score

train_predictions = model.predict(train_x)
precision_score(train_y, train_predictions)

0.993058600029227

In [54]:
#재현율
from sklearn.metrics import recall_score

recall_score(train_y, train_predictions)

0.9641742338251986

In [13]:
from xgboost import plot_importance
from xgboost import XGBClassifier
import sklearn
from sklearn.metrics import classification_report, accuracy_score


In [14]:
xgb=XGBClassifier(base_score=0.6, colsample_bylevel=1, colsample_bytree=1,
       gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=10,
       min_child_weight=1, missing=None, n_estimators=100, nthread=-1,
       objective='binary:logistic', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=1, seed=0, silent=True, subsample=1)
xgb.fit(train_x,train_y)
xgb_pred=xgb.predict(test_x)

[19:12:13] WARNING: C:\Users\Administrator\workspace\xgboost-win64_release_1.1.0\src\learner.cc:480: 
Parameters: { silent } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.




In [15]:
xgb=XGBClassifier(n_estimators=100,base_score=0.7, learning_rate=0.1,max_depth=4)
xgb.fit(train_x,train_y)
xgb_pred=xgb.predict(test_x)

In [16]:
print(classification_report(test_y, xgb_pred))

              precision    recall  f1-score   support

           0       0.57      0.69      0.62      3803
           1       0.56      0.43      0.49      3492

    accuracy                           0.57      7295
   macro avg       0.57      0.56      0.56      7295
weighted avg       0.57      0.57      0.56      7295



In [17]:
print(xgb_pred)

[0 1 0 ... 0 0 0]


In [18]:
print('정확도:',metrics.accuracy_score(test_y,xgb_pred))

정확도: 0.5664153529814941


In [19]:
model = RandomForestClassifier(n_estimators=100)
model.fit(train_x, train_y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [20]:
y_pred=model.predict(test_x)
print(y_pred)
print(list(y_pred))

[0 0 0 ... 1 1 1]
[0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 

In [21]:
print('정확도:',metrics.accuracy_score(test_y,y_pred))

정확도: 0.5351610692254969


In [22]:
xgb=XGBClassifier(base_score=0.6,booster='gbtree', colsample_bytree=0.9,
       gamma=0, learning_rate=0.01, max_depth=5,cv=5,random_state=1,scoring='roc_auc',
       min_child_weight=1, n_estimators=100, nthread=1,
       objective='binary:logistic',scale_pos_weight=1, subsample=0.9)
xgb.fit(train_x,train_y)
xgb_pred=xgb.predict(test_x)

[19:12:36] WARNING: C:\Users\Administrator\workspace\xgboost-win64_release_1.1.0\src\learner.cc:480: 
Parameters: { cv, scoring } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.




In [23]:
print('정확도:',metrics.accuracy_score(test_y,xgb_pred))

정확도: 0.5317340644276902
